name: "ci"
run-name: "build & test"

on: [push]

env:
  GH_TOKEN: ${{github.token}}

jobs:
  build-test:
    runs-on: debian-latest
    container: debian:latest
    steps:
      - uses: actions/checkout@v4
      - name: "Install dependencies"
        run: |
          apt update
          apt install gcc -y
      - name: "Build"
        run: make build
      - name: "Test"
        run: make run-tests
